apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysql 
        image: mysql:5.6
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-db-password
                key: db-password
        ports:
          - containerPort: 3306
        volumeMounts: #this is inside your container
          - name: mysql-persistent-volume #i am capturing the volume of mysql container
            mountPath: /var/lib/mysql #this is inisde your pod
          - name: usermanagement-db-creation-script
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: task-pv-volume
        - name: usermanagement-db-creation-script
          configMap:
            name: usermanagement-db-creation-script

      




