apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: mysqlstorage
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce #ReadWriteMany read
  hostPath:
    path: "/mnt/data"