apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: mysqlstorage
  capcacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"