apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysqlstorage
  resources:
    requests:
      storage: 5Gi